- name: Make sure that apache is installed
  yum:
    name: "{{ package_name }}"
    state: latest
    update_cache: yes
- name: Mausre that apache is running
  service: 
    name: "{{ service_name }}"
    state: started
    enabled: yes
