- hosts: webservers
  remote_user: ubuntu
  become_user: root
  become: yes
  become_method: sudo
  vars:
    package_name: apache2
    service_name: apache2
    document_root: /var/www/html
    index_file: index.html
    website_name: devops.com
    list_of_websites:
      - web1.com
      - web3.com
      - mycompany.com
    database:
      name: wpdb
      username: wpuser
      password: DEVOPS123
      host: localhost
  tasks:
    - name: Make sure that Apache is installed
      apt:
        name: "{{ package_name }}"
        update_cache: yes
        state: present
    - name: Make sure that Apache is Running
      service:
        name: "{{ service_name }}"
        state: started
    - name: Make sure that index.html file is present in /var/www/html
      copy:
        src: index.html
        dest: "{{ document_root }}/{{ index_file }}"
    - name: Make sure that basil.com configuration is present in the remote machine
      template:
        src: test.conf.j2
        dest: /etc/apache2/sites-enabled/basil.com.conf
      notify: Restart Apache
    - name: Make sure that wp-config.php is present in the /var/www/html
      template: 
        src: wp-config.j2
        dest: /var/www/html/wp-config.php

  handlers:
    - name: Restart Apache
      service:
        name: "{{ service_name }}"
        state: restarted
